# Generated by Django 5.1.1 on 2024-09-24 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layuplist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='course_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='professor_rating',
            field=models.FloatField(default=0),
        ),
    ]
