# Generated by Django 5.1.1 on 2024-09-20 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layuplist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.FloatField(),
        ),
    ]
