# Generated by Django 5.1.1 on 2024-09-24 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layuplist', '0002_review_course_rating_review_professor_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='layup',
            field=models.BooleanField(default=False),
        ),
    ]
