# Generated by Django 5.1.1 on 2024-09-20 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layuplist', '0002_alter_course_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='url',
            field=models.URLField(default='https://dartmouth.smartcatalogiq.com/en/current/orc/departments-programs-undergraduate/womens-gender-and-sexualities-studies-program/wgss-womens-gender-and-sexualities-studies/wgss-34-04/'),
            preserve_default=False,
        ),
    ]
