# Generated by Django 5.1.1 on 2024-09-23 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layuplist', '0002_alter_course_code_alter_course_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='layup',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
