# Generated by Django 5.1.1 on 2024-09-27 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layuplist', '0002_course_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='number',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
