# Generated by Django 5.1.1 on 2024-09-20 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layuplist', '0003_course_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='disribs',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='layup',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
