# Generated by Django 5.1.1 on 2024-09-20 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layuplist', '0005_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.FloatField(unique=True),
        ),
    ]
