# Generated by Django 5.1.1 on 2024-09-20 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layuplist', '0008_alter_course_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['short_name']},
        ),
        migrations.AlterField(
            model_name='course',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='layuplist.department'),
        ),
    ]
