# Generated by Django 5.1.1 on 2024-09-20 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layuplist', '0009_alter_department_options_alter_course_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='url',
            field=models.URLField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='url',
            field=models.URLField(max_length=400),
        ),
    ]
