# Generated by Django 5.1.1 on 2024-09-20 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layuplist', '0010_department_url_alter_course_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='disribs',
        ),
        migrations.AddField(
            model_name='course',
            name='distribs',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
